In [1]:
import numpy as np


In [17]:
img = np.array([
    [2, 2, 6, 4, 8, 5, 4, 4,],
    [1, 1, 9, 3, 3, 5, 5, 7,],
    [0, 0, 0, 6, 0, 4, 9, 8,],
    [3, 3, 8, 5, 6, 7, 7, 5,],
    [4, 2, 5, 7, 1, 6, 0, 6,],
    [1, 2, 7, 0, 4, 0, 2, 1,],
    [8, 6, 7, 2, 6, 8, 1, 0,],
    [8, 9, 0, 1, 4, 2, 1, 2,],
])
column, row = img.shape

mask = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1],
])
img_convolution = np.zeros((column -2 , row -2))
print(img[0:3, 0:3])
print("{} , {}".format(column, row))
for index_column in range(0, column - 2):
    for index_row in range(0, column - 2):
        next_column = index_column + 3
        next_row = index_row + 3
        sub_img = img[index_column:next_column, index_row:next_row]
        sub_img = (sub_img * mask) / 16
        img_convolution[index_column, index_row] = sub_img.sum()
print("New imagen with convolution")
print(img_convolution)

[[2 2 6]
 [1 1 9]
 [0 0 0]]
8 , 8
New imagen with convolution
[[1.3125 1.9375 2.4375 2.375  2.6875 3.1875]
 [1.5625 2.1875 2.5    2.4375 2.875  3.5625]
 [1.5625 2.25   2.375  2.625  2.5    3.25  ]
 [2.1875 2.4375 2.6875 2.25   2.0625 2.125 ]
 [2.625  2.375  2.4375 2.125  1.75   1.5   ]
 [3.     2.125  1.9375 1.6875 1.75   1.0625]]
